services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    working_dir: /workspace/frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3001
    network_mode: host
    command: "sleep infinity"
    security_opt:
      - label=disable
    restart: unless-stopped
    # Add memory limits to prevent OOM
    mem_limit: 2g
    mem_reservation: 1g
    memswap_limit: 4g
    user: "1000:1000"
    privileged: true
    init: true

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    working_dir: /workspace/backend
    environment:
      - NODE_ENV=development
      - PORT=3001
    network_mode: host
    command: npm run dev
    security_opt:
      - label=disable
    restart: unless-stopped
    # Add memory limits to prevent OOM
    mem_limit: 2g
    mem_reservation: 1g
    memswap_limit: 4g
    user: "1000:1000"
    privileged: true
    init: true
