services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ../:/workspace
    working_dir: /workspace/frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    network_mode: host
    command: npm start
    security_opt:
      - label=disable
    restart: unless-stopped
    # Add memory limits to prevent OOM
    mem_limit: 2g
    mem_reservation: 1g
    memswap_limit: 4g

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ../:/workspace
    working_dir: /workspace/backend
    environment:
      - NODE_ENV=development
      - PORT=3001
    network_mode: host
    command: npm run dev
    security_opt:
      - label=disable
    restart: unless-stopped
    # Add memory limits to prevent OOM
    mem_limit: 2g
    mem_reservation: 1g
    memswap_limit: 4g
